version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: suaSenhaAqui
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
